[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd_err.log

[program:gateway]
command=/app/YourPlaceGateway -g -d -du
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/gateway.log
stderr_logfile=/var/log/supervisor/gateway_err.log
