name: Ubuntu

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        lfs: true

    - name: Extract Version From Go Code
      id: get_version
      run: |
        VERSION=$(grep -oE '^\s*version\s*=\s*"[^"]*"' main.go | grep -oE '"[^"]*"' | tr -d '"')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version found: $VERSION"
    
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '20.x'

    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '1.25.1'

    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2
        verbose: false
        arch: amd64

    - name: Install Make
      run: |
        sudo apt-get update
        sudo apt-get install -y make

    - name: Install NPM Dependencies
      run: |
        npm install package.json

    - name: Run Make Build
      run: |
        make clean build

    - name: Configure AWS CLI for DigitalOcean Spaces
      run: |
        aws configure set aws_access_key_id ${{ secrets.S3_UPLOAD_ID }}
        aws configure set aws_secret_access_key ${{ secrets.S3_UPLOAD_SECRET }}
        aws configure set default.region us-east-1
        aws configure set default.s3.endpoint_url https://nyc3.digitaloceanspaces.com
        aws configure set default.s3.addressing_style path

    - name: Upload to DigitalOcean
      run: |
        for file in target/YourPlace-*; do
          aws s3 cp "$file" s3://yourplace-downloads/linux/ --acl public-read --endpoint-url https://nyc3.digitaloceanspaces.com
        done
        