name: Windows

on:
  workflow_dispatch:
  push:
    branches: [ chad ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
    - name: Check Out Code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        lfs: true
    
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '20.x'

    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: '1.25.1'

    - name: Choco Install
      uses: ConorMacBride/install-package@3e7ad059e07782ee54fa35f827df52aae0626f30 # v1.1.0
      with:
        choco: make awscli

    - name: Make Install
      run: make install

    - name: Make Build
      run: make build

    - name: Configure AWS CLI for DigitalOcean Spaces
      run: |
        aws configure set aws_access_key_id ${{ secrets.S3_UPLOAD_ID }}
        aws configure set aws_secret_access_key ${{ secrets.S3_UPLOAD_SECRET }}
        aws configure set default.region us-east-1
        aws configure set default.s3.endpoint_url https://nyc3.digitaloceanspaces.com
        aws configure set default.s3.addressing_style path

    - name: Upload to DigitalOcean
      run: |
          $files = Get-ChildItem target\YourPlace-*.exe
          foreach ($file in $files) {
            aws s3 cp $file.FullName s3://yourplace-downloads/windows/ --acl=public-read --endpoint=https://nyc3.digitaloceanspaces.com
          }
